base_dir: "/var/www/oslc.co/public/ns/"
compression: true
ns_definitions:

  - prefix: "/ns/core"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/core/v3.0/os/core-vocab.html"
    files:
      rdfxml: "core/core-vocab.rdf"
      ntriples: "core/core-vocab.nt"
      jsonld: "core/core-vocab.jsonld"
      turtle: "core/core-vocab.ttl"

  - prefix: "/ns/core/shapes/3.0"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/core/v3.0/os/core-shapes.html"
    files:
      rdfxml: "core/core-shapes.rdf"
      ntriples: "core/core-shapes.nt"
      jsonld: "core/core-shapes.jsonld"
      turtle: "core/core-shapes.ttl"

  - prefix: "/ns/config"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/config/v1.0/psd01/config-vocab.html"
    files:
      rdfxml: "config/config-vocab.rdf"
      ntriples: "config/config-vocab.nt"
      jsonld: "config/config-vocab.jsonld"
      turtle: "config/config-vocab.ttl"

  - prefix: "/ns/config/shapes/1.0"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/config/v1.0/psd01/config-resources.html"
    files:
      rdfxml: "config/config-shapes.rdf"
      ntriples: "config/config-shapes.nt"
      jsonld: "config/config-shapes.jsonld"
      turtle: "config/config-shapes.ttl"

  - prefix: "/ns/cm"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/cm/v3.0/os/change-mgt-vocab.html"
    files:
      rdfxml: "cm/change-mgt-vocab.rdf"
      ntriples: "cm/change-mgt-vocab.nt"
      jsonld: "cm/change-mgt-vocab.jsonld"
      turtle: "cm/change-mgt-vocab.ttl"

  - prefix: "/ns/cm/shapes/3.0"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/cm/v3.0/os/change-mgt-shapes.html"
    files:
      rdfxml: "cm/change-mgt-shapes.rdf"
      ntriples: "cm/change-mgt-shapes.nt"
      jsonld: "cm/change-mgt-shapes.jsonld"
      turtle: "cm/change-mgt-shapes.ttl"

  - prefix: "/ns/rm"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/os/requirements-management-vocab.html"
    files:
      rdfxml: "rm/requirements-management-vocab.rdf"
      ntriples: "rm/requirements-management-vocab.nt"
      jsonld: "rm/requirements-management-vocab.jsonld"
      turtle: "rm/requirements-management-vocab.ttl"

  - prefix: "/ns/rm/shapes/2.1"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/os/requirements-management-shapes.html"
    files:
      rdfxml: "rm/requirements-management-shapes.rdf"
      ntriples: "rm/requirements-management-shapes.nt"
      jsonld: "rm/requirements-management-shapes.jsonld"
      turtle: "rm/requirements-management-shapes.ttl"

  - prefix: "/ns/qm"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/qm/v2.1/os/quality-management-vocab.html"
    files:
      rdfxml: "qm/quality-management-vocab.rdf"
      ntriples: "qm/quality-management-vocab.nt"
      jsonld: "qm/quality-management-vocab.jsonld"
      turtle: "qm/quality-management-vocab.ttl"

  - prefix: "/ns/qm/shapes/2.1"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/qm/v2.1/os/quality-management-shapes.html"
    files:
      rdfxml: "qm/quality-management-shapes.rdf"
      ntriples: "qm/quality-management-shapes.nt"
      jsonld: "qm/quality-management-shapes.jsonld"
      turtle: "qm/quality-management-shapes.ttl"

  - prefix: "/ns/am"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/architecture-management/OSLC-Architecture-Management-Vocabulary/index.html"
    files:
      rdfxml: "am/am.rdf"
      ntriples: "am/am.nt"
      jsonld: "am/am.jsonld"
      turtle: "am/am.ttl"

  - prefix: "/ns/core/trs"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/psd01/tracked-resource-set-vocab.html"
    files:
      rdfxml: "trs/trs-vocab.rdf"
      ntriples: "trs/trs-vocab.nt"
      jsonld: "trs/trs-vocab.jsonld"
      turtle: "trs/trs-vocab.ttl"

  - prefix: "/ns/core/trspatch"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/psd01/tracked-resource-set-vocab.html"
    files:
      rdfxml: "trs/trs-vocab.rdf"
      ntriples: "trs/trs-vocab.nt"
      jsonld: "trs/trs-vocab.jsonld"
      turtle: "trs/trs-vocab.ttl"

  - prefix: "/ns/trs/shapes/3.0"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/psd01/tracked-resource-set-shapes.html"
    files:
      rdfxml: "trs/trs-shapes.rdf"
      ntriples: "trs/trs-shapes.nt"
      jsonld: "trs/trs-shapes.jsonld"
      turtle: "trs/trs-shapes.ttl"

  - prefix: "/ns/promcode"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open.org/oslc-promcode/promcode/v1.0/os/promcode-vocab.html"
    files:
      rdfxml: "promcode/promcode-vocab.rdf"
      ntriples: "promcode/promcode-vocab.nt"
      jsonld: "promcode/promcode-vocab.jsonld"
      turtle: "promcode/promcode-shapes.ttl"
   
  - prefix: "/ns/promcode/shapes/1.0"
    core_version: "3.0"
    html_uri: "https://docs.oasis-open.org/oslc-promcode/promcode/v1.0/os/promcode-shapes.html"
    files:
      rdfxml: "promcode/promcode-shapes.rdf"
      ntriples: "promcode/promcode-shapes.nt"
      jsonld: "promcode/promcode-shapes.jsonld"
      turtle: "promcode/promcode-shapes.ttl"
      
  - prefix: "/ns/asset"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/asset-management/OSLC-Asset-Management-Vocabulary/index.html"
    files:
      rdfxml: "asset/asset.rdf"
      ntriples: "asset/asset.nt"
      jsonld: "asset/asset.jsonld"
      turtle: "asset/asset.ttl"

  - prefix: "/ns/auto"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/automation/OSLC-Automation-Vocabulary/index.html"
    files:
      rdfxml: "auto/automation-vocab.rdf"
      ntriples: "auto/automation-vocab.nt"
      jsonld: "auto/automation-vocab.jsonld"
      turtle: "auto/automation-vocab.ttl"

  - prefix: "/ns/perfmon"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/performance-monitoring/OSLC-Performance-Monitoring-Vocabulary/index.html"
    files:
      rdfxml: "perfmon/performance-monitoring-vocab.rdf"
      ntriples: "perfmon/performance-monitoring-vocab.nt"
      jsonld: "perfmon/performance-monitoring-vocab.jsonld"
      turtle: "perfmon/performance-monitoring-vocab.ttl"

  - prefix: "/ns/ems"
    core_version: "2.0"
    html_uri: "https://archive.open-services.net/wiki/estimation-and-measurement/EMS-1.0-REST-API-Data-Model/index.html"
    files:
      rdfxml: "ems/ems.rdf"
      ntriples: "ems/ems.nt"
      jsonld: "ems/ems.jsonld"
      turtle: "ems/ems.ttl"
